### ISSUE TITLE
Graph-node-edge global settings

### ISSUE THREAD

**Issue by rytis-paskauskas** [fgm/grafizzi#9]
Is there a way to specify per-graph (sub-graph) properties? I'm talking about stuff like
`graph G {
  graph [K=...];
  node [style=...];
  edge [style=...];
`. Pretending as if they were just  `Node` with special names doesn't work as it yields quoted node names:
`graph G {
    "graph" [K=...];
    "node" [style=...];
    "edge" [style=...]`
so that won't do it. What am I missing? An example would be great!

**Comment by fgm** [comment]
Could you provide a short code fragment showing how you use it to generate this invalid graphviz syntax ?

**Comment by rytis-paskauskas** [comment]
Something along these lines:
``` 
$node = new Node($dic, 'node');
$node->setAttribute(new Attribute($dic, 'style', 'folder'));
$g->addChild($node);
``` 
which yields `"node" [style=folder]` where, I believe, the presence of quotes is a problem.

**Comment by fgm** [comment]
AIUI Graphviz does not allow embedding a graph within a graph: you need to use a subgraph for that, which you can create with a Subgraph or Cluster element: like `graph G { subgraph SG [K=...]; node [style=...]; edge [style=...];`.

**Comment by rytis-paskauskas** [comment]
What's I'm talking about is just valid [DOT language semantics](https://www.graphviz.org/doc/info/lang.html) specifically, the `attr_stmt` section of the following:
```
graph | : | [ strict ] (graph \| digraph) [ ID ] '{' stmt_list '}'
-- | -- | --
stmt_list | : | [ stmt [ ';' ] stmt_list ]
stmt | : | node_stmt
  | \| | edge_stmt
  | \| | attr_stmt
  | \| | ID '=' ID
  | \| | subgraph
attr_stmt | : | (graph \| node \| edge) attr_list
attr_list | : | '[' [ a_list ] ']' [ attr_list ]
a_list | : | ID '=' ID [ (';' \| ',') ] [ a_list ]
edge_stmt | : | (node_id \| subgraph) edgeRHS [ attr_list ]
edgeRHS | : | edgeop (node_id \| subgraph) [ edgeRHS ]
node_stmt | : | node_id [ attr_list ]
node_id | : | ID [ port ]
port | : | ':' ID [ ':' compass_pt ]
  | \| | ':' compass_pt
subgraph | : | [ subgraph [ ID ] ] '{' stmt_list '}'
compass_pt | : | (n \| ne \| e \| se \| s \| sw \| w \| nw \| c \| _)
```
You can see that `attr_stmt` can be `edge`, `node`,  or other `attr_list`. That's not an embedding, but a special type of node, if you wish, that fixes some global attributes within a graph (or a subgraph).
There are quite important features!

**Comment by fgm** [comment]
OK, so we seem talking past each other:

* I'm referring to the initial example where there is this: `graph G { graph [K=...]; ` which AIUI is invalid, including in regard to the grammar you linked to (which, I must, I had never seen before, thanks for that), because it nests a graph within a graph
* you appear to be referring to `"node" [attributes]`, where:
  * you would have a statement like `node [attributes]` which is used to set generic attributes on nodes
  * the code wraps the "node" label in double quotes, precisely to avoid this interpretation, allowing the use of a node named "node".

Are we in agreement on these interpretations ?

**Comment by rytis-paskauskas** [comment]
Sorry but we are not.
- I think you are fixated with this case `graph { graph[...]; }`... thinking that seeing two `graph`s means there are two nested graphs. That's **not** the case. You can't nest graphs like that according to the grammar (as you also mentioned previously). At most we could say is, *what were they thinking (designers of the DOT language), allowing a non bijecting keyword*? Because if you look carefully at the grammar you'll notice, that `graph` appears it two places. Hey, that's not our problem.  But the example I gave previuosly **is correct** and pertinent.

- I think we are in agreement on this part right, but just in case: The sentence `graph { node []};` semantically is **not identical** to `graph { "node" [];}`  and likewise `graph { edge []};` is **not identical** to `graph { "edge" [];}` In both cases, the first instance has a *special keyword* which must be entered without quotes. AIUI this is not currently possible in graphizzi. These special keywords are the point of my request. They are part of the DOT language and I am asking to consider implementing this important feature.

To make a step in this direction, a simple idea is as follows: we could have additionally, three special `Node` classes (because structurally, they are like them) constructable, for example, something like so:
```
NodeNode(Container $dic, array $attributes = array())
NodeEdge(Container $dic, array $attributes = array())
NodeGraph(Container $dic, array $attributes = array())
``` 
where the name is omitted, because they construct nodes with special names, which are respectively, 
`node`, `edge`, `graph` without the quotes.

What do you think about this suggestion?

**Comment by rytis-paskauskas** [comment]
and please don't reply telling me about 'invalid graphviz syntax'...

**Comment by fgm** [comment]
Seems we agree on the second part, albeit with different wordings. And I finally understood what you meant about that second graph keyword: for some reason I had until now misread your square braces `[K=...]` for curly ones.

Grafizzi doesn't include support for this notation, indeed. However, you can use the equivalent
alternate notation. Instead of this:

```dot
graph g {
   graph [attr=value];
}
```

You can use this, which is a bit more compact:

```dot
graph g {
   attr=value;
}
```

You just need to set attributes on the original graph object. There are examples of this in IG09Test, IG16Test and IG16872Test. Does this solve your need ?

**Comment by rytis-paskauskas** [comment]
No need to waste anyone's time.
I hoped you were taking it seriously, but you are obviously not.

**Comment by fgm** [comment]
Strange: I don't even understand your reaction. I suppose this means the proposed workaround does not solve your issue ?
